In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [45]:
'Obtain the MNist dataset'
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784',version=1)
X,y=mnist['data'],mnist['target']
X.shape

(70000, 784)

In [46]:
digits = pd.DataFrame(X)

In [47]:
col_names = ['pixel '+str(i) for i in range(784)]
digits.columns = col_names
digits.head()

pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   pixel 8  pixel 9  ...  pixel 774  pixel 775  pixel 776  pixel 777  \
0      0.0      0.0  ...        0.0        0.0        0.0        0.0   
1      0.0      0.0  ...        0.0        0.0        0.0        0.0   
2      0.0      0.0  ...        0.0        0.0        0.0        0.0   
3      0.0      0.0  ...        0.0        0.0        0.0        0.0   
4      0.0      0.0  ...        0.0        0.0        0.0        0.0   

   pixel 778  pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  
0        0.0        0.0        0.0        0.0        0.0        0.0  
1        0.0        0.0        0.0        0.0        0.0        0.0  
2        0.0        0.0        0.0        0.0        0.0        0.0  
3        0.0        0.0        0.0        0.0        0.0        0.0  
4        0.0        0.0        0.0        0.0        0.0        0.0  

[5 rows x 784 columns]

In [48]:
y = y.astype(np.uint8)
digits['label'] = y 
digits.head()

pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   pixel 8  pixel 9  ...  pixel 775  pixel 776  pixel 777  pixel 778  \
0      0.0      0.0  ...        0.0        0.0        0.0        0.0   
1      0.0      0.0  ...        0.0        0.0        0.0        0.0   
2      0.0      0.0  ...        0.0        0.0        0.0        0.0   
3      0.0      0.0  ...        0.0        0.0        0.0        0.0   
4      0.0      0.0  ...        0.0        0.0        0.0        0.0   

   pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  label  
0        0.0        0.0        0.0        0.0        0.0      5  
1        0.0        0.0        0.0        0.0        0.0      0  
2        0.0        0.0        0.0        0.0        0.0      4  
3        0.0        0.0        0.0        0.0        0.0      1  
4        0.0        0.0        0.0        0.0        0.0      9  

[5 rows x 785 columns]

## Problem 1: Classification of handwritten digits

In [40]:
# load the data
url = 'https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Theory/master/Data/digits.csv'
data = pd.read_csv(url)
data.head(5) # display first 5 rows of the dataset

pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   pixel 8  pixel 9  ...  pixel 775  pixel 776  pixel 777  pixel 778  \
0      0.0      0.0  ...        0.0        0.0        0.0        0.0   
1      0.0      0.0  ...        0.0        0.0        0.0        0.0   
2      0.0      0.0  ...        0.0        0.0        0.0        0.0   
3      0.0      0.0  ...        0.0        0.0        0.0        0.0   
4      0.0      0.0  ...        0.0        0.0        0.0        0.0   

   pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  label  
0        0.0        0.0        0.0        0.0        0.0      5  
1        0.0        0.0        0.0        0.0        0.0      0  
2        0.0        0.0        0.0        0.0        0.0      4  
3        0.0        0.0        0.0        0.0        0.0      1  
4        0.0        0.0        0.0        0.0        0.0      9  

[5 rows x 785 columns]

In [42]:
X = data.iloc[:,0:784].to_numpy() # pixels
y = data['label'].to_numpy()

In [43]:
X.shape

(5000, 784)

In [44]:
X.max()

0.0039215686274509795

In [34]:
data = pd.read_csv('https://raw.githubusercontent.com/um-perez-alvaro/Data-Science-Practice/master/Data/digits.csv')
data.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel776  pixel777  pixel778  pixel779  pixel780  pixel781  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel782  pixel783  pixel784  class  
0       0.0       0.0       0.0      5  
1       0.0       0.0       0.0      0  
2       0.0       0.0       0.0      4  
3       0.0       0.0       0.0      1  
4       0.0       0.0       0.0      9  

[5 rows x 785 columns]

In [35]:
X = data.iloc[:,0:784].to_numpy()

In [36]:
X.max()

255.0

In [37]:
X.min()

0.0

In [38]:
X = X /255

In [39]:
X.max()

1.0

This dataset contains 5,000 images, and each image has 784 features. 
This is because each image is 28×28  pixels, and each feature simply represents one pixel's intensity, from 0 (white) to 1 (black).

Let's take a peek at one digit from the dataset. All we need to do is grab an instance's feature vector, reshape it to a  28×28  array, and display it using imshow()

## Load data

In [18]:
data = pd.read_csv('digits.csv')
data.head()

pixel 0  pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   pixel 8  pixel 9  ...  pixel 775  pixel 776  pixel 777  pixel 778  \
0      0.0      0.0  ...        0.0        0.0        0.0        0.0   
1      0.0      0.0  ...        0.0        0.0        0.0        0.0   
2      0.0      0.0  ...        0.0        0.0        0.0        0.0   
3      0.0      0.0  ...        0.0        0.0        0.0        0.0   
4      0.0      0.0  ...        0.0        0.0        0.0        0.0   

   pixel 779  pixel 780  pixel 781  pixel 782  pixel 783  label  
0        0.0        0.0        0.0        0.0        0.0      5  
1        0.0        0.0        0.0        0.0        0.0      0  
2        0.0        0.0        0.0        0.0        0.0      4  
3        0.0        0.0        0.0        0.0        0.0      1  
4        0.0        0.0        0.0        0.0        0.0      9  

[5 rows x 785 columns]

In [19]:
data.shape

(5000, 785)

In [5]:
X_train,y_train = X[:60000],y[:60000]
X_test,y_test = X[60000:], y[60000:]

In [6]:
y_5_train = np.zeros((len(y_train),1))
y_5_train[y_train==0]=1

## normal equations

In [10]:
X_train.shape

(60000, 784)

In [11]:
X_train.max()

1.0

In [12]:
C = 1
M = X_train.T.dot(X_train) + C*np.identity(784)
b = X_train.T.dot(y_5_train)

In [13]:
theta = np.linalg.solve(M,b)

In [14]:
y_5_test = np.zeros((len(y_test),1))
y_5_test[y_test==0]=1

In [15]:
y_5_test_pred = X_test.dot(theta)

In [16]:
y_5_test_pred[y_5_test_pred>=0.5] = 1
y_5_test_pred[y_5_test_pred<0.5] = 0

In [17]:
'confusion matrix'
C = np.zeros((2,2))
for i in range(2):
    for j in range(2):
        C[i,j] = sum(y_5_test_pred[y_5_test==i]==j)
C.astype(int)

array([[8981,   39],
       [ 171,  809]])

In [18]:
y_test[3]

array([0], dtype=uint8)

In [20]:
X_new = X_test[3]

In [21]:
y_pred = X_new.dot(theta)

In [22]:
y_pred

array([0.84277884])

In [23]:
y_test[0]

array([7], dtype=uint8)

In [28]:
X_new = X_test[2]

In [29]:
y_pred = X_new.dot(theta)
y_pred

array([0.00215575])

## Gradient Descent