In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Neural network layers

In [7]:
class layer_dense:
      
    # initialization (weights and biases)
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))

    # forward pass: pass the data through the layer
    def forward(self, inputs):
        self.output = inputs.dot(self.weights) + self.biases

In [8]:
X = np.random.randn(10,2)
X

array([[-2.05549297, -0.76379982],
       [ 0.65620053, -0.45714017],
       [-0.06712164, -0.15144689],
       [ 1.42022374, -0.23109866],
       [ 1.40175426, -0.2212946 ],
       [-0.32321032,  1.75847582],
       [ 0.72643631,  1.1688175 ],
       [-1.02328841, -0.63058377],
       [-0.52226426,  0.33961414],
       [-0.55001917,  0.83251677]])

In [9]:
# create 1 dense layer
layer1 = layer(n_inputs = 2, n_neurons = 5)

In [10]:
layer1.forward(X)

In [10]:
layer1.output

array([[-0.26010442, -0.22189632, -0.06639757,  0.16420568,  0.03741141],
       [-0.14006761, -0.16938984, -0.14533857,  0.00252236, -0.00322501],
       [-0.1378963 , -0.03924949,  0.1369573 ,  0.22201155,  0.0565509 ],
       [ 0.62082597,  0.59191967,  0.29527924, -0.28469335, -0.06011905],
       [-0.53703171, -0.50307939, -0.2357744 ,  0.26167174,  0.05619555],
       [ 0.16235258,  0.17344191,  0.11817413, -0.04234494, -0.00698702],
       [-0.01269847, -0.04927239, -0.08766053, -0.05816021, -0.01617794],
       [-0.26628093, -0.34216344, -0.32052863, -0.02987485, -0.01556355],
       [-0.21520564, -0.31037144, -0.3333626 , -0.08240042, -0.02842768],
       [-0.23972595, -0.22410294, -0.10422186,  0.11761184,  0.02530392]])

In [6]:
# create multiple layers
layer1 = layer(n_inputs = 2, n_neurons = 5)
layer2 = layer(n_inputs = 5, n_neurons = 10)
layer3 = layer(n_inputs =10, n_neurons = 2)

NameError: name 'layer' is not defined

In [14]:
layer1.forward(X)
layer2.forward(layer1.output)
layer3.forward(layer2.output)

In [15]:
layer3.output

array([[-0.00649856,  0.01241683],
       [ 0.00803505,  0.00037554],
       [-0.02156642,  0.01649763],
       [ 0.00111169, -0.02175852],
       [-0.00303001,  0.0199534 ],
       [-0.0040202 , -0.00333142],
       [ 0.00856856, -0.00425556],
       [ 0.01993063, -0.00183314],
       [ 0.02392998, -0.00576136],
       [-0.00146053,  0.00896608]])