In [1]:
import numpy as np

In [2]:
X = np.array([[1,1,1,1],[0,1,0,1],[1,1,-1,0]])
X

array([[ 1,  1,  1,  1],
       [ 0,  1,  0,  1],
       [ 1,  1, -1,  0]])

In [3]:
y = np.array([0,1,2])
y

array([0, 1, 2])

In [4]:
X_new = np.array([[1,1,1,0],[-1,1,-1,1]])
X_new

array([[ 1,  1,  1,  0],
       [-1,  1, -1,  1]])

In [5]:
dist = np.zeros((2,3))
for i in range(2):
    dist[i] = np.linalg.norm(X-X_new[i], axis=1)
dist

array([[1.        , 1.73205081, 2.        ],
       [2.82842712, 1.41421356, 2.23606798]])

In [6]:
knn = np.argsort(dist,axis=1)[:,0:2]
knn

array([[0, 1],
       [1, 2]], dtype=int64)

In [7]:
labels = y[knn]
labels

array([[0, 1],
       [1, 2]])

In [22]:
np.apply_along_axis(np.bincount, 1,labels, minlength=3)

array([[1., 1., 0.],
       [0., 1., 1.]])

In [9]:
np.argmax(np.apply_along_axis(np.bincount, 1,labels, minlength=3),axis=1)

array([0, 1], dtype=int64)

In [36]:
## weighted knn
i = 0
weights = 1/dist[i,knn[i]]
np.bincount(labels[i], minlength=3,weights=weights)

array([1.        , 0.57735027, 0.        ])

In [38]:
dist[0]

array([1.        , 1.73205081, 2.        ])

In [37]:
knn[0]

array([0, 1], dtype=int64)

In [34]:
i = 1
weights = 1/dist[i,knn[i]]
np.bincount(labels[i], minlength=3,weights=weights)

array([0.        , 0.70710678, 0.4472136 ])

In [32]:
dist[1]

array([2.82842712, 1.41421356, 2.23606798])

In [33]:
knn[1]

array([1, 2], dtype=int64)

In [31]:
1/dist[i,knn[1]]

array([1.41421356, 2.23606798])

In [36]:
## distance matrix

In [10]:
np.sqrt(np.square(X_new).sum(1).reshape([-1,1])+np.square(X).sum(1).reshape([1,-1])-2*X_new.dot(X.T))

array([[1.        , 1.73205081, 2.        ],
       [2.82842712, 1.41421356, 2.23606798]])

In [11]:
X_new

array([[ 1,  1,  1,  0],
       [-1,  1, -1,  1]])

In [14]:
np.square(X_new), np.square(X_new).sum(axis=1)

(array([[1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=int32),
 array([3, 4], dtype=int32))

In [17]:
np.square(X_new).sum(axis=1).reshape([2,1])

array([[3],
       [4]], dtype=int32)

In [18]:
np.square(X).sum(1).reshape([1,3])

array([[4, 2, 3]], dtype=int32)